import { Pencil, Plus, Users } from "lucide-react";
import { useMemo, useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { Button, DataTable, Drawer, EmptyState, FormField, Input, Modal, RoleBadge, Select, StatusBadge, TableToolbar, Toast, UserAvatar, type TableColumn } from "@/components/ui";
import { useAdminActions, useAdminDepartments, useAdminUsers } from "@/features/admin/hooks";
import type { AdminDepartment } from "@/features/admin/types";

const schema = z.object({ name: z.string().min(2, "Укажите название"), code: z.string().min(2, "Укажите код"), headId: z.string().optional(), parentId: z.string().optional(), status: z.enum(["active", "disabled"]) });
type DepartmentValues = z.infer<typeof schema>;
const PAGE_SIZE = 8;

function DepartmentForm({ department, onClose, onSaved }: { department?: AdminDepartment; onClose: () => void; onSaved: (message: string) => void }) {
  const departments = useAdminDepartments(); const users = useAdminUsers(); const actions = useAdminActions();
  const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<DepartmentValues>({ resolver: zodResolver(schema), defaultValues: { name: department?.name ?? "", code: department?.code ?? "", headId: department?.headId ?? "", parentId: department?.parentId ?? "", status: department?.status ?? "active" } });
  const submit = (values: DepartmentValues) => { const value = { ...values, code: values.code.toUpperCase(), headId: values.headId || undefined, parentId: values.parentId || undefined }; if (department) actions.departments.update(department.id, value); else actions.departments.create(value); onSaved(department ? "Подразделение обновлено" : "Подразделение создано"); onClose(); };
  return <form className="admin-form" onSubmit={handleSubmit(submit)}><FormField label="Название" htmlFor="department-name" error={errors.name?.message}><Input id="department-name" aria-label="Название" {...register("name")} /></FormField><FormField label="Код" htmlFor="department-code" error={errors.code?.message}><Input id="department-code" aria-label="Код" {...register("code")} /></FormField><FormField label="Руководитель" htmlFor="department-head"><Select id="department-head" aria-label="Руководитель" options={[{ value: "", label: "Не назначен" }, ...users.map((user) => ({ value: user.id, label: user.fullName }))]} {...register("headId")} /></FormField><FormField label="Родительское подразделение" htmlFor="department-parent"><Select id="department-parent" aria-label="Родительское подразделение" options={[{ value: "", label: "Нет родительского" }, ...departments.filter((item) => item.id !== department?.id).map((item) => ({ value: item.id, label: item.name }))]} {...register("parentId")} /></FormField><FormField label="Статус" htmlFor="department-status" error={errors.status?.message}><Select id="department-status" aria-label="Статус" options={[{ value: "active", label: "Активно" }, { value: "disabled", label: "Отключено" }]} {...register("status")} /></FormField><div className="form-actions"><Button type="button" variant="secondary" onClick={onClose}>Отмена</Button><Button type="submit" loading={isSubmitting}>{department ? "Сохранить" : "Создать"}</Button></div></form>;
}

export function DepartmentsPage() {
  const departments = useAdminDepartments(); const users = useAdminUsers(); const actions = useAdminActions();
  const [query, setQuery] = useState(""); const [status, setStatus] = useState<AdminDepartment["status"] | "all">("all"); const [page, setPage] = useState(1); const [editor, setEditor] = useState<AdminDepartment | "create" | null>(null); const [employeesDepartment, setEmployeesDepartment] = useState<AdminDepartment | null>(null); const [toast, setToast] = useState<string | null>(null);
  const userMap = useMemo(() => new Map(users.map((user) => [user.id, user])), [users]); const departmentMap = useMemo(() => new Map(departments.map((department) => [department.id, department.name])), [departments]);
  const filtered = useMemo(() => departments.filter((department) => { const needle = query.trim().toLowerCase(); return (!needle || department.name.toLowerCase().includes(needle) || department.code.toLowerCase().includes(needle)) && (status === "all" || department.status === status); }), [departments, query, status]);
  const pageCount = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const visible = filtered.slice((Math.min(page, pageCount) - 1) * PAGE_SIZE, Math.min(page, pageCount) * PAGE_SIZE);
  const reset = () => { setQuery(""); setStatus("all"); setPage(1); }; const toggle = (department: AdminDepartment) => { const next = department.status === "active" ? "disabled" : "active"; actions.departments.update(department.id, { status: next }); setToast(next === "active" ? "Подразделение активировано" : "Подразделение отключено"); };
  const columns: TableColumn<AdminDepartment>[] = [{ id: "name", header: "Название", cell: (department) => department.name }, { id: "code", header: "Код", cell: (department) => department.code }, { id: "head", header: "Руководитель", cell: (department) => userMap.get(department.headId ?? "")?.fullName ?? "Не назначен" }, { id: "parent", header: "Родительское", cell: (department) => department.parentId ? departmentMap.get(department.parentId) ?? "Не назначено" : "—" }, { id: "count", header: "Сотрудники", cell: (department) => users.filter((user) => user.departmentId === department.id).length }, { id: "status", header: "Статус", cell: (department) => <StatusBadge status={department.status} /> }, { id: "actions", header: "Действия", cell: (department) => <div className="admin-actions"><Button variant="ghost" icon={<Pencil size={15} />} onClick={() => setEditor(department)}>Изменить</Button><Button variant="secondary" icon={<Users size={15} />} onClick={() => setEmployeesDepartment(department)}>Сотрудники</Button><Button variant={department.status === "active" ? "danger" : "secondary"} onClick={() => toggle(department)}>{department.status === "active" ? "Отключить" : "Активировать"}</Button></div> }];
  const employees = employeesDepartment ? users.filter((user) => user.departmentId === employeesDepartment.id) : [];
  return <div className="page-stack admin-page"><section className="page-hero"><div><h1>Подразделения</h1><p>Организационная структура и ответственные сотрудники.</p></div><Button icon={<Plus size={18} />} onClick={() => setEditor("create")}>Создать подразделение</Button></section><section className="content-card"><DataTable columns={columns} rows={visible} toolbar={<TableToolbar><Input aria-label="Поиск подразделений" placeholder="Поиск по названию и коду" value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} /><Select aria-label="Фильтр по статусу" value={status} options={[{ value: "all", label: "Все статусы" }, { value: "active", label: "Активные" }, { value: "disabled", label: "Отключенные" }]} onChange={(event) => { setStatus(event.target.value as AdminDepartment["status"] | "all"); setPage(1); }} /><Button variant="secondary" onClick={reset}>Сбросить</Button></TableToolbar>} empty={<EmptyState title="Подразделения не найдены" />} pagination={{ page: Math.min(page, pageCount), pageCount, onPageChange: setPage }} renderMobileCard={(department) => <div className="admin-mobile-card"><strong>{department.name}</strong><span>{department.code}</span><StatusBadge status={department.status} /><div className="admin-actions"><Button variant="ghost" onClick={() => setEditor(department)}>Изменить</Button><Button variant="secondary" onClick={() => setEmployeesDepartment(department)}>Сотрудники</Button><Button variant={department.status === "active" ? "danger" : "secondary"} onClick={() => toggle(department)}>{department.status === "active" ? "Отключить" : "Активировать"}</Button></div></div>} /></section>{editor && <Modal isOpen onClose={() => setEditor(null)} title={editor === "create" ? "Новое подразделение" : "Редактирование подразделения"}><DepartmentForm department={editor === "create" ? undefined : editor} onClose={() => setEditor(null)} onSaved={setToast} /></Modal>}{employeesDepartment && <Drawer isOpen onClose={() => setEmployeesDepartment(null)} title={`Сотрудники: ${employeesDepartment.name}`}>{employees.length ? <div className="employee-list">{employees.map((user) => <article key={user.id} className="employee-list__item"><UserAvatar name={user.fullName} src={user.avatarUrl} /><div><strong>{user.fullName}</strong><span>{user.position}</span></div><RoleBadge role={user.role} /><StatusBadge status={user.status} /></article>)}</div> : <EmptyState title="Сотрудников нет" description="В этом подразделении пока нет пользователей." />}</Drawer>}{toast && <Toast message={toast} kind="success" onClose={() => setToast(null)} />}</div>;
}
