import { Pencil, Plus, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { Button, Checkbox, ConfirmDialog, DataTable, DepartmentBadge, EmptyState, FormField, Input, Modal, Select, StatusBadge, TableToolbar, Toast, type TableColumn } from "@/components/ui";
import { useAdminActions, useAdminCategories, useAdminDepartments } from "@/features/admin/hooks";
import type { AdminCategory } from "@/features/admin/types";

const schema = z.object({ name: z.string().min(2, "Укажите название"), code: z.string().min(2, "Укажите код"), description: z.string(), retentionPeriod: z.string().min(1, "Укажите срок хранения"), departmentIds: z.array(z.string()), status: z.enum(["active", "disabled"]) });
type CategoryValues = z.infer<typeof schema>;
const PAGE_SIZE = 8;

function CategoryForm({ category, onClose, onSaved }: { category?: AdminCategory; onClose: () => void; onSaved: (message: string) => void }) {
  const departments = useAdminDepartments(); const actions = useAdminActions();
  const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<CategoryValues>({ resolver: zodResolver(schema), defaultValues: { name: category?.name ?? "", code: category?.code ?? "", description: category?.description ?? "", retentionPeriod: category?.retentionPeriod ?? "5 лет", departmentIds: category?.departmentIds ?? [], status: category?.status ?? "active" } });
  const submit = async (values: CategoryValues) => { const value = { ...values, code: values.code.toUpperCase() }; try { if (category) await actions.categories.update(category.id, value); else await actions.categories.create({ ...value, documentCount: 0 }); onSaved(category ? "Категория обновлена" : "Категория создана"); onClose(); } catch { /* no success is shown when the backend mutation rejects */ } };
  return <form className="admin-form" onSubmit={handleSubmit(submit)}><FormField label="Название" htmlFor="category-name" error={errors.name?.message}><Input id="category-name" aria-label="Название" {...register("name")} /></FormField><FormField label="Код" htmlFor="category-code" error={errors.code?.message}><Input id="category-code" aria-label="Код" {...register("code")} /></FormField><FormField label="Описание" htmlFor="category-description"><Input id="category-description" aria-label="Описание" {...register("description")} /></FormField><FormField label="Срок хранения" htmlFor="category-retention" error={errors.retentionPeriod?.message}><Input id="category-retention" aria-label="Срок хранения" {...register("retentionPeriod")} /></FormField><FormField label="Доступные подразделения" error={errors.departmentIds?.message}>{departments.map((department) => <Checkbox key={department.id} label={department.name} value={department.id} {...register("departmentIds")} />)}</FormField><FormField label="Статус" htmlFor="category-status" error={errors.status?.message}><Select id="category-status" aria-label="Статус" options={[{ value: "active", label: "Активна" }, { value: "disabled", label: "Отключена" }]} {...register("status")} /></FormField><div className="form-actions"><Button type="button" variant="secondary" onClick={onClose}>Отмена</Button><Button type="submit" loading={isSubmitting}>{category ? "Сохранить" : "Создать"}</Button></div></form>;
}

export default function CategoriesPage() {
  const categories = useAdminCategories(); const departments = useAdminDepartments(); const actions = useAdminActions();
  const [query, setQuery] = useState(""); const [status, setStatus] = useState<AdminCategory["status"] | "all">("all"); const [page, setPage] = useState(1); const [editor, setEditor] = useState<AdminCategory | "create" | null>(null); const [deleteCandidate, setDeleteCandidate] = useState<AdminCategory | null>(null); const [toast, setToast] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const departmentMap = useMemo(() => new Map(departments.map((department) => [department.id, department.name])), [departments]);
  const filtered = useMemo(() => categories.filter((category) => { const needle = query.trim().toLowerCase(); return (!needle || [category.name, category.code, category.description].some((value) => value.toLowerCase().includes(needle))) && (status === "all" || category.status === status); }), [categories, query, status]);
  const pageCount = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const visible = filtered.slice((Math.min(page, pageCount) - 1) * PAGE_SIZE, Math.min(page, pageCount) * PAGE_SIZE);
  const reset = () => { setQuery(""); setStatus("all"); setPage(1); }; const toggle = async (category: AdminCategory) => { const next = category.status === "active" ? "disabled" : "active"; try { await actions.categories.update(category.id, { status: next }); setToast(next === "active" ? "Категория активирована" : "Категория отключена"); } catch (reason) { setError(reason instanceof Error ? reason.message : "Не удалось изменить категорию."); } }; const remove = async () => { if (!deleteCandidate) return; try { await actions.categories.remove(deleteCandidate.id); setToast("Категория удалена"); setDeleteCandidate(null); } catch (reason) { setError(reason instanceof Error ? reason.message : "Не удалось удалить категорию."); } };
  const columns: TableColumn<AdminCategory>[] = [{ id: "name", header: "Название", cell: (category) => category.name }, { id: "code", header: "Код", cell: (category) => category.code }, { id: "description", header: "Описание", cell: (category) => category.description || "—" }, { id: "retention", header: "Срок хранения", cell: (category) => category.retentionPeriod }, { id: "departments", header: "Подразделения", cell: (category) => <div className="category-departments">{category.departmentIds.length ? category.departmentIds.map((id) => <DepartmentBadge key={id} department={departmentMap.get(id) ?? "Удалено"} />) : "Все"}</div> }, { id: "status", header: "Статус", cell: (category) => <StatusBadge status={category.status} /> }, { id: "count", header: "Документы", cell: (category) => category.documentCount }, { id: "actions", header: "Действия", cell: (category) => <div className="admin-actions"><Button variant="ghost" icon={<Pencil size={15} />} onClick={() => setEditor(category)}>Изменить</Button><Button variant={category.status === "active" ? "danger" : "secondary"} onClick={() => void toggle(category)}>{category.status === "active" ? "Отключить" : "Активировать"}</Button><Button variant="danger" icon={<Trash2 size={15} />} onClick={() => setDeleteCandidate(category)}>Удалить</Button></div> }];
  return <div className="page-stack admin-page"><section className="page-hero"><div><h1>Категории документов</h1><p>Настройка классификации, сроков хранения и доступов.</p></div><Button icon={<Plus size={18} />} onClick={() => setEditor("create")}>Создать категорию</Button></section><section className="content-card"><DataTable columns={columns} rows={visible} toolbar={<TableToolbar><Input aria-label="Поиск категорий" placeholder="Поиск по названию, коду и описанию" value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} /><Select aria-label="Фильтр по статусу" value={status} options={[{ value: "all", label: "Все статусы" }, { value: "active", label: "Активные" }, { value: "disabled", label: "Отключенные" }]} onChange={(event) => { setStatus(event.target.value as AdminCategory["status"] | "all"); setPage(1); }} /><Button variant="secondary" onClick={reset}>Сбросить</Button></TableToolbar>} empty={<EmptyState title="Категории не найдены" />} pagination={{ page: Math.min(page, pageCount), pageCount, onPageChange: setPage }} renderMobileCard={(category) => <div className="admin-mobile-card"><strong>{category.name}</strong><span>{category.code}</span><span>{category.description}</span><StatusBadge status={category.status} /><div className="admin-actions"><Button variant="ghost" onClick={() => setEditor(category)}>Изменить</Button><Button variant={category.status === "active" ? "danger" : "secondary"} onClick={() => void toggle(category)}>{category.status === "active" ? "Отключить" : "Активировать"}</Button><Button variant="danger" onClick={() => setDeleteCandidate(category)}>Удалить</Button></div></div>} /></section>{editor && <Modal isOpen onClose={() => setEditor(null)} title={editor === "create" ? "Новая категория" : "Редактирование категории"}><CategoryForm category={editor === "create" ? undefined : editor} onClose={() => setEditor(null)} onSaved={setToast} /></Modal>}{deleteCandidate && <ConfirmDialog isOpen onClose={() => setDeleteCandidate(null)} onConfirm={() => void remove()} title="Удалить категорию" description="Категория будет удалена на сервере." confirmLabel="Удалить" />}{toast && <Toast message={toast} kind="success" onClose={() => setToast(null)} />}{error && <Toast kind="error" message={error} onClose={() => setError(null)} />}</div>;
}
