import { RotateCcw } from "lucide-react";
import { useMemo, useState } from "react";
import { AuditActionBadge, Button, DataTable, EmptyState, Input, Select, StatusIcon, TableToolbar, type TableColumn } from "@/components/ui";
import { useAdminAuditLogs } from "@/features/admin/hooks";
import type { AdminAuditLog } from "@/features/admin/types";

const PAGE_SIZE = 10;
const AUDIT_NOW = Date.now();
type Period = "all" | "today" | "week" | "month";
const periodDays: Record<Exclude<Period, "all">, number> = { today: 1, week: 7, month: 30 };
const asDate = (value: string) => new Date(value.replace(" ", "T"));

export function AuditPage() {
  const logs = useAdminAuditLogs();
  const [query, setQuery] = useState(""); const [user, setUser] = useState("all"); const [action, setAction] = useState<AdminAuditLog["action"] | "all">("all"); const [department, setDepartment] = useState("all"); const [document, setDocument] = useState("all"); const [result, setResult] = useState<AdminAuditLog["result"] | "all">("all"); const [period, setPeriod] = useState<Period>("all"); const [page, setPage] = useState(1);
  const users = useMemo(() => [...new Set(logs.map((log) => log.userName))], [logs]); const departments = useMemo(() => [...new Set(logs.map((log) => log.department))], [logs]); const documents = useMemo(() => [...new Set(logs.map((log) => log.document))], [logs]);
  const filtered = useMemo(() => logs.filter((log) => { const needle = query.trim().toLowerCase(); const matchesQuery = !needle || [log.userName, log.action, log.object, log.document, log.department].some((value) => value.toLowerCase().includes(needle)); const matchesPeriod = period === "all" || asDate(log.dateTime) >= new Date(AUDIT_NOW - periodDays[period] * 86400000); return matchesQuery && (user === "all" || log.userName === user) && (action === "all" || log.action === action) && (department === "all" || log.department === department) && (document === "all" || log.document === document) && (result === "all" || log.result === result) && matchesPeriod; }), [action, department, document, logs, period, query, result, user]);
  const pageCount = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const visible = filtered.slice((Math.min(page, pageCount) - 1) * PAGE_SIZE, Math.min(page, pageCount) * PAGE_SIZE);
  const reset = () => { setQuery(""); setUser("all"); setAction("all"); setDepartment("all"); setDocument("all"); setResult("all"); setPeriod("all"); setPage(1); };
  const columns: TableColumn<AdminAuditLog>[] = [{ id: "date", header: "Дата и время", cell: (log) => log.dateTime }, { id: "user", header: "Пользователь", cell: (log) => log.userName }, { id: "role", header: "Роль", cell: (log) => log.role }, { id: "action", header: "Действие", cell: (log) => <AuditActionBadge action={log.action} /> }, { id: "object", header: "Объект", cell: (log) => log.object }, { id: "document", header: "Документ", cell: (log) => log.document }, { id: "department", header: "Подразделение", cell: (log) => log.department }, { id: "result", header: "Результат", cell: (log) => <span className={`audit-result audit-result--${log.result}`}><StatusIcon status={log.result} />{log.result === "success" ? "Успешно" : "Ошибка"}</span> }];
  const setFilter = <T,>(setter: (value: T) => void) => (value: T) => { setter(value); setPage(1); };
  return <div className="page-stack admin-page audit-page"><section className="page-hero"><div><h1>Журнал действий</h1><p>Только чтение. В журнале {logs.length} записей.</p></div></section><section className="content-card"><DataTable columns={columns} rows={visible} toolbar={<TableToolbar><Input aria-label="Поиск по журналу" placeholder="Поиск по журналу" value={query} onChange={(event) => setFilter(setQuery)(event.target.value)} /><Select aria-label="Пользователь" value={user} options={[{ value: "all", label: "Все пользователи" }, ...users.map((value) => ({ value, label: value }))]} onChange={(event) => setFilter(setUser)(event.target.value)} /><Select aria-label="Действие" value={action} options={[{ value: "all", label: "Все действия" }, ...[...new Set(logs.map((log) => log.action))].map((value) => ({ value, label: value }))]} onChange={(event) => setFilter(setAction)(event.target.value as AdminAuditLog["action"] | "all")} /><Select aria-label="Подразделение" value={department} options={[{ value: "all", label: "Все подразделения" }, ...departments.map((value) => ({ value, label: value }))]} onChange={(event) => setFilter(setDepartment)(event.target.value)} /><Select aria-label="Документ" value={document} options={[{ value: "all", label: "Все документы" }, ...documents.map((value) => ({ value, label: value }))]} onChange={(event) => setFilter(setDocument)(event.target.value)} /><Select aria-label="Результат" value={result} options={[{ value: "all", label: "Все результаты" }, { value: "success", label: "Успешно" }, { value: "error", label: "Ошибка" }]} onChange={(event) => setFilter(setResult)(event.target.value as AdminAuditLog["result"] | "all")} /><Select aria-label="Период" value={period} options={[{ value: "all", label: "Всё время" }, { value: "today", label: "Сегодня" }, { value: "week", label: "За неделю" }, { value: "month", label: "За месяц" }]} onChange={(event) => setFilter(setPeriod)(event.target.value as Period)} /><Button variant="secondary" icon={<RotateCcw size={16} />} onClick={reset}>Сбросить</Button></TableToolbar>} empty={<EmptyState title="Записи не найдены" description="Измените параметры фильтрации." />} pagination={{ page: Math.min(page, pageCount), pageCount, onPageChange: setPage }} renderMobileCard={(log) => <div className="audit-mobile-card"><strong>{log.document}</strong><span>{log.dateTime}</span><span>{log.userName} · {log.role}</span><AuditActionBadge action={log.action} /><span>{log.department}</span><span className={`audit-result audit-result--${log.result}`}><StatusIcon status={log.result} />{log.result === "success" ? "Успешно" : "Ошибка"}</span></div>} /></section></div>;
}
