import { RotateCcw, Save, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { Button, Checkbox, ConfirmDialog, DataTable, EmptyState, Input, RoleBadge, TableToolbar, Toast, type TableColumn } from "@/components/ui";
import { useAdminActions, useAdminRoles } from "@/features/admin/hooks";
import type { AdminPermission, AdminRole } from "@/features/admin/types";

const permissions: { id: AdminPermission; label: string; critical?: boolean }[] = [
  { id: "documents:read", label: "Просмотр документов" }, { id: "documents:create", label: "Создание документов" }, { id: "documents:update", label: "Редактирование документов" }, { id: "documents:approve", label: "Согласование" }, { id: "documents:return", label: "Возврат" }, { id: "documents:archive", label: "Архивирование" }, { id: "users:manage", label: "Управление пользователями", critical: true }, { id: "departments:manage", label: "Управление подразделениями", critical: true }, { id: "categories:manage", label: "Управление категориями", critical: true }, { id: "audit:read", label: "Просмотр журнала" }, { id: "settings:manage", label: "Доступ к настройкам", critical: true },
];
const cloneRoles = (roles: AdminRole[]) => roles.map((role) => ({ ...role, permissions: [...role.permissions] }));

export function RolesPage() {
  const savedRoles = useAdminRoles(); const actions = useAdminActions();
  const [draft, setDraft] = useState(() => cloneRoles(savedRoles)); const [query, setQuery] = useState(""); const [pending, setPending] = useState<{ roleId: AdminRole["id"]; permission: AdminPermission; checked: boolean } | null>(null); const [saving, setSaving] = useState(false); const [toast, setToast] = useState<string | null>(null);
  const dirty = JSON.stringify(draft) !== JSON.stringify(savedRoles); const rows = useMemo(() => permissions.filter((permission) => permission.label.toLowerCase().includes(query.trim().toLowerCase())), [query]);
  const apply = (roleId: AdminRole["id"], permission: AdminPermission, checked: boolean) => setDraft((roles) => roles.map((role) => role.id === roleId ? { ...role, permissions: checked ? [...new Set([...role.permissions, permission])] : role.permissions.filter((item) => item !== permission) } : role));
  const requestChange = (role: AdminRole, permission: typeof permissions[number]) => { const checked = !role.permissions.includes(permission.id); if (permission.critical) setPending({ roleId: role.id, permission: permission.id, checked }); else apply(role.id, permission.id, checked); };
  const save = async () => { setSaving(true); await new Promise((resolve) => window.setTimeout(resolve, 150)); draft.forEach((role) => actions.roles.update(role.id, { permissions: role.permissions })); setSaving(false); setToast("Права ролей сохранены"); };
  const columns: TableColumn<{ id: AdminPermission; label: string; critical?: boolean }>[] = [{ id: "permission", header: "Право", cell: (permission) => <span className="roles-permission">{permission.label}{permission.critical && <span className="roles-permission__critical">Критическое</span>}</span> }, ...draft.map((role) => ({ id: role.id, header: <RoleBadge role={role.name} />, cell: (permission: typeof permissions[number]) => <Checkbox aria-label={`${role.name}: ${permission.label}`} label="" checked={role.permissions.includes(permission.id)} onChange={() => requestChange(role, permission)} /> }))];
  return <div className="page-stack admin-page roles-page"><section className="page-hero"><div><h1>Роли и права</h1><p>Матрица прав применяется только после сохранения.</p></div><div className="roles-header-actions"><Button variant="secondary" icon={<RotateCcw size={16} />} disabled={!dirty || saving} onClick={() => setDraft(cloneRoles(savedRoles))}>Отменить изменения</Button><Button icon={<Save size={16} />} loading={saving} disabled={!dirty || saving} onClick={save}>Сохранить</Button></div></section><section className="content-card"><div className="roles-list">{draft.map((role) => <RoleBadge key={role.id} role={role.name} />)}</div>{dirty && <p className="roles-dirty">Есть несохранённые изменения.</p>}<DataTable columns={columns} rows={rows} toolbar={<TableToolbar><Input aria-label="Поиск права" placeholder="Поиск права" value={query} onChange={(event) => setQuery(event.target.value)} /><Button variant="secondary" icon={<Search size={16} />} onClick={() => setQuery("")}>Сбросить</Button></TableToolbar>} empty={<EmptyState title="Права не найдены" />} /></section>{pending && <ConfirmDialog isOpen onClose={() => setPending(null)} title="Подтвердите критическое право" description="Это изменение попадёт в черновик и будет применено только после сохранения." confirmLabel="Подтвердить" onConfirm={() => { apply(pending.roleId, pending.permission, pending.checked); setPending(null); }} />}{toast && <Toast message={toast} kind="success" onClose={() => setToast(null)} />}</div>;
}
