import { zodResolver } from "@hookform/resolvers/zod";
import { ArrowLeft, Save } from "lucide-react";
import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import { Link, useNavigate } from "react-router-dom";
import { z } from "zod";
import { Button, FormField, Input, PageError, Select, UnsavedChangesDialog } from "@/components/ui";
import { useAdminActions, useAdminDepartments, useAdminUsers } from "@/features/admin/hooks";
import type { AdminUser } from "@/features/admin/types";
import { useUnsavedChangesGuard } from "./useUnsavedChangesGuard";

const schema = z.object({ fullName: z.string().min(2, "Укажите ФИО"), email: z.string().email("Введите корректный email"), phone: z.string().min(5, "Укажите телефон"), position: z.string().min(2, "Укажите должность"), departmentId: z.string().min(1, "Выберите подразделение"), managerId: z.string().optional(), role: z.enum(["admin", "rector", "department_head", "employee", "approver"]), status: z.enum(["active", "blocked", "pending"]), temporaryPassword: z.string() });
type UserFormValues = z.infer<typeof schema>;
const roleOptions = [{ value: "admin", label: "Администратор" }, { value: "rector", label: "Ректор" }, { value: "department_head", label: "Руководитель подразделения" }, { value: "employee", label: "Сотрудник" }, { value: "approver", label: "Согласующий" }];
const statusOptions = [{ value: "active", label: "Активен" }, { value: "blocked", label: "Заблокирован" }, { value: "pending", label: "Ожидает" }];

export function UserForm({ user }: { user?: AdminUser }) {
  const createMode = !user;
  const navigate = useNavigate();
  const departments = useAdminDepartments();
  const users = useAdminUsers();
  const actions = useAdminActions();
  const [savedToast, setSavedToast] = useState<string | null>(null);
  const form = useForm<UserFormValues>({ resolver: zodResolver(schema.superRefine((values, ctx) => { if (createMode && values.temporaryPassword.trim().length < 6) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["temporaryPassword"], message: "Пароль должен содержать минимум 6 символов" }); })), defaultValues: { fullName: user?.fullName ?? "", email: user?.email ?? "", phone: user?.phone ?? "", position: user?.position ?? "", departmentId: user?.departmentId ?? "", managerId: user?.managerId ?? "", role: user?.role ?? "employee", status: user?.status ?? "active", temporaryPassword: "" } });
  const { register, handleSubmit, reset, formState: { errors, isDirty, isSubmitting } } = form;
  const unsavedChangesGuard = useUnsavedChangesGuard(isDirty && !isSubmitting && !savedToast);
  useEffect(() => { if (savedToast) navigate("/users", { state: { toast: savedToast } }); }, [navigate, savedToast]);
  const submit = async (values: UserFormValues) => { const base = { fullName: values.fullName, email: values.email, phone: values.phone, position: values.position, departmentId: values.departmentId, managerId: values.managerId || undefined, role: values.role, status: values.status }; if (user) actions.users.update(user.id, { ...base, ...(values.temporaryPassword ? { temporaryPassword: values.temporaryPassword } : {}) }); else actions.users.create({ ...base, temporaryPassword: values.temporaryPassword, lastActive: "Только что" }); reset(values); setSavedToast(createMode ? "Пользователь создан" : "Пользователь сохранён"); };
  if (!createMode && !user) return <PageError description="Пользователь не найден." action={<Link to="/users"><Button>Вернуться к пользователям</Button></Link>} />;
  return <div className="page-stack users-form-page"><Link className="users-back" to="/users"><ArrowLeft size={16} />К списку пользователей</Link><section className="page-heading"><h1>{createMode ? "Создать пользователя" : "Редактировать пользователя"}</h1><p>Заполните данные учетной записи сотрудника.</p></section><section className="content-card"><form className="users-form" onSubmit={handleSubmit(submit)}><FormField label="ФИО" htmlFor="fullName" error={errors.fullName?.message}><Input id="fullName" aria-label="ФИО" {...register("fullName")} /></FormField><FormField label="Email" htmlFor="email" error={errors.email?.message}><Input id="email" type="email" aria-label="Email" {...register("email")} /></FormField><FormField label="Телефон" htmlFor="phone" error={errors.phone?.message}><Input id="phone" aria-label="Телефон" {...register("phone")} /></FormField><FormField label="Должность" htmlFor="position" error={errors.position?.message}><Input id="position" aria-label="Должность" {...register("position")} /></FormField><FormField label="Подразделение" htmlFor="departmentId" error={errors.departmentId?.message}><Select id="departmentId" aria-label="Подразделение" options={departments.map((department) => ({ value: department.id, label: department.name }))} {...register("departmentId")} /></FormField><FormField label="Руководитель" htmlFor="managerId"><Select id="managerId" aria-label="Руководитель" options={[{ value: "", label: "Не назначен" }, ...users.filter((item) => item.id !== user?.id).map((item) => ({ value: item.id, label: item.fullName }))]} {...register("managerId")} /></FormField><FormField label="Роль" htmlFor="role" error={errors.role?.message}><Select id="role" aria-label="Роль" options={roleOptions} {...register("role")} /></FormField><FormField label="Статус" htmlFor="status" error={errors.status?.message}><Select id="status" aria-label="Статус" options={statusOptions} {...register("status")} /></FormField><FormField label={createMode ? "Временный пароль" : "Новый временный пароль"} htmlFor="temporaryPassword" error={errors.temporaryPassword?.message} hint={createMode ? "Минимум 6 символов" : "Оставьте пустым, чтобы не менять пароль"}><Input id="temporaryPassword" type="password" aria-label="Временный пароль" {...register("temporaryPassword")} /></FormField><div className="form-actions"><Link to="/users"><Button variant="secondary" type="button">Отмена</Button></Link><Button type="submit" loading={isSubmitting} icon={<Save size={16} />}>{createMode ? "Создать" : "Сохранить"}</Button></div></form></section>{unsavedChangesGuard.isDialogOpen && <UnsavedChangesDialog isOpen onClose={unsavedChangesGuard.cancelNavigation} onConfirm={unsavedChangesGuard.confirmNavigation} />}</div>;
}
