import { Ban, Pencil, Plus, RotateCcw, Search } from "lucide-react";
import { Link, useLocation } from "react-router-dom";
import { useMemo, useState } from "react";
import { Button, DataTable, DepartmentBadge, EmptyState, Input, PageError, RoleBadge, Select, StatusBadge, TableToolbar, Toast, UserAvatar, type TableColumn } from "@/components/ui";
import { useAdminActions, useAdminDepartments, useAdminUsersQuery } from "@/features/admin/hooks";
import type { AdminUser, AdminUserStatus } from "@/features/admin/types";

const PAGE_SIZE = 20;
const roles: Record<string, string> = { admin: "Администратор", manager: "Руководитель", office: "Канцелярия", employee: "Сотрудник" };

export function UsersPage() {
  const location = useLocation(); const [search, setSearch] = useState(""); const [role, setRole] = useState("all"); const [department, setDepartment] = useState("all"); const [status, setStatus] = useState<AdminUserStatus | "all">("all"); const [page, setPage] = useState(1); const [toast, setToast] = useState<string | null>((location.state as { toast?: string } | null)?.toast ?? null); const [error, setError] = useState<string | null>(null);
  const departments = useAdminDepartments(); const actions = useAdminActions();
  const query = useAdminUsersQuery({ page, page_size: PAGE_SIZE, search: search || undefined, role: role === "all" ? undefined : role, department: department === "all" ? undefined : department, status: status === "all" ? undefined : status === "pending" ? "invited" : status });
  const items = query.data?.results ?? []; const pageCount = Math.max(1, Math.ceil((query.data?.count ?? 0) / PAGE_SIZE)); const departmentMap = useMemo(() => new Map(departments.map((item) => [item.id, item.name])), [departments]);
  const setFilter = (callback: () => void) => { callback(); setPage(1); };
  const changeStatus = async (user: AdminUser) => { const next: AdminUserStatus = user.status === "blocked" ? "active" : "blocked"; try { await actions.users.update(user.id, { status: next }, user.status); setToast(next === "active" ? "Пользователь активирован" : "Пользователь заблокирован"); } catch (reason) { setError(reason instanceof Error ? reason.message : "Не удалось изменить статус."); } };
  const columns: TableColumn<AdminUser>[] = [{ id: "name", header: "ФИО", cell: (item) => <span className="users-name"><UserAvatar name={item.fullName} size="sm" />{item.fullName}</span> }, { id: "email", header: "Email", cell: (item) => item.email }, { id: "phone", header: "Телефон", cell: (item) => item.phone }, { id: "position", header: "Должность", cell: (item) => item.position }, { id: "department", header: "Подразделение", cell: (item) => <DepartmentBadge department={departmentMap.get(item.departmentId) ?? "Не назначено"} /> }, { id: "role", header: "Роль", cell: (item) => <RoleBadge role={roles[item.role] ?? item.role} /> }, { id: "status", header: "Статус", cell: (item) => <StatusBadge status={item.status} /> }, { id: "actions", header: "Действия", cell: (item) => <div className="users-actions"><Link to={`/users/${item.id}/edit`}><Button variant="ghost" icon={<Pencil size={15} />}>Изменить</Button></Link><Button variant={item.status === "blocked" ? "secondary" : "danger"} icon={item.status === "blocked" ? <RotateCcw size={15} /> : <Ban size={15} />} onClick={() => void changeStatus(item)}>{item.status === "blocked" ? "Активировать" : "Заблокировать"}</Button></div> }];
  if (query.isError) return <PageError description={query.error instanceof Error ? query.error.message : "Не удалось загрузить пользователей."} />;
  return <div className="page-stack users-page"><section className="page-hero"><div><h1>Пользователи</h1><p>Данные загружаются с сервера.</p></div><Link to="/users/create"><Button icon={<Plus size={18} />}>Создать пользователя</Button></Link></section><section className="content-card"><DataTable loading={query.isLoading} columns={columns} rows={items} toolbar={<TableToolbar><Input aria-label="Поиск пользователей" value={search} onChange={(event) => setFilter(() => setSearch(event.target.value))} placeholder="ФИО или email" /><Select aria-label="Роль" value={role} onChange={(event) => setFilter(() => setRole(event.target.value))} options={[{ value: "all", label: "Все роли" }, ...Object.entries(roles).map(([value, label]) => ({ value, label }))]} /><Select aria-label="Подразделение" value={department} onChange={(event) => setFilter(() => setDepartment(event.target.value))} options={[{ value: "all", label: "Все подразделения" }, ...departments.map((item) => ({ value: item.id, label: item.name }))]} /><Select aria-label="Статус" value={status} onChange={(event) => setFilter(() => setStatus(event.target.value as AdminUserStatus | "all"))} options={[{ value: "all", label: "Все статусы" }, { value: "active", label: "Активные" }, { value: "blocked", label: "Заблокированные" }, { value: "pending", label: "Ожидающие" }]} /><Button variant="secondary" icon={<Search size={16} />} onClick={() => { setSearch(""); setRole("all"); setDepartment("all"); setStatus("all"); setPage(1); }}>Сбросить</Button></TableToolbar>} empty={<EmptyState title="Пользователи не найдены" />} pagination={{ page, pageCount, onPageChange: setPage }} renderMobileCard={(item) => <div className="users-mobile-card"><strong>{item.fullName}</strong><span>{item.email}</span><StatusBadge status={item.status} /><div className="users-actions"><Link to={`/users/${item.id}/edit`}><Button variant="ghost">Изменить</Button></Link><Button onClick={() => void changeStatus(item)}>{item.status === "blocked" ? "Активировать" : "Заблокировать"}</Button></div></div>} /></section>{toast && <Toast kind="success" message={toast} onClose={() => setToast(null)} />}{error && <Toast kind="error" message={error} onClose={() => setError(null)} />}</div>;
}
