import { Search, X } from "lucide-react";
import { useEffect, type ChangeEventHandler, type ReactNode } from "react";
import { Link } from "react-router-dom";
import { FormField, UserAvatar } from "./AdminUi";
import { Button, IconButton } from "./Button";
import { Input, type InputProps } from "./Input";

export function DatePicker({ label, error, ...props }: InputProps) { return <Input type="date" label={label} error={error} {...props} />; }
export interface TabItem { id: string; label: ReactNode; disabled?: boolean; }
export function Tabs({ items, activeId, onChange, ariaLabel = "Вкладки", className = "" }: { items: TabItem[]; activeId: string; onChange: (id: string) => void; ariaLabel?: string; className?: string }) { return <div className={`ui-tabs ${className}`} role="tablist" aria-label={ariaLabel}>{items.map((item) => <Button key={item.id} type="button" role="tab" aria-selected={item.id === activeId} disabled={item.disabled} variant={item.id === activeId ? "primary" : "ghost"} onClick={() => onChange(item.id)}>{item.label}</Button>)}</div>; }
export function Avatar({ name, src, size = "md", className = "" }: { name: string; src?: string; size?: "sm" | "md" | "lg"; className?: string }) { return <span className={className}><UserAvatar name={name} src={src} size={size} /></span>; }
export function Dropdown({ isOpen, onClose, trigger, children, className = "", ariaLabel = "Меню" }: { isOpen: boolean; onClose: () => void; trigger: ReactNode; children: ReactNode; className?: string; ariaLabel?: string }) { useEffect(() => { const closeOnEscape = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; if (isOpen) window.addEventListener("keydown", closeOnEscape); return () => window.removeEventListener("keydown", closeOnEscape); }, [isOpen, onClose]); return <div className={`ui-dropdown ${className}`}>{trigger}{isOpen && <div className="ui-dropdown__menu" role="menu" aria-label={ariaLabel}>{children}</div>}</div>; }
export function Tooltip({ content, children, className = "" }: { content: string; children: ReactNode; className?: string }) { return <span className={`ui-tooltip ${className}`} data-tooltip={content}>{children}</span>; }
export interface BreadcrumbItem { label: string; to?: string; }
export function Breadcrumbs({ items, className = "", ariaLabel = "Навигационная цепочка" }: { items: BreadcrumbItem[]; className?: string; ariaLabel?: string }) { return <nav className={`ui-breadcrumbs ${className}`} aria-label={ariaLabel}>{items.map((item, index) => <span key={`${item.label}-${index}`}>{item.to ? <Link to={item.to}>{item.label}</Link> : <span aria-current="page">{item.label}</span>}{index < items.length - 1 && <span aria-hidden="true">/</span>}</span>)}</nav>; }
export function PageHeader({ title, description, actions, breadcrumbs, className = "" }: { title: string; description?: string; actions?: ReactNode; breadcrumbs?: BreadcrumbItem[]; className?: string }) { return <header className={`ui-page-header ${className}`}>{breadcrumbs && <Breadcrumbs items={breadcrumbs} />}<div className="ui-page-header__row"><div><h1>{title}</h1>{description && <p>{description}</p>}</div>{actions && <div className="ui-page-header__actions">{actions}</div>}</div></header>; }
export function SearchInput({ className = "", onClear, value, onChange, ...props }: Omit<InputProps, "type"> & { onClear?: () => void; value: string; onChange: ChangeEventHandler<HTMLInputElement> }) { return <div className={`ui-search-input ${className}`}><Search size={17} aria-hidden="true" /><Input {...props} value={value} onChange={onChange} aria-label={props["aria-label"] ?? "Поиск"} />{value && onClear && <IconButton type="button" aria-label="Очистить поиск" onClick={onClear}><X size={16} /></IconButton>}</div>; }
export function FilterPanel({ children, onReset, className = "", resetLabel = "Сбросить" }: { children: ReactNode; onReset?: () => void; className?: string; resetLabel?: string }) { return <section className={`ui-filter-panel ${className}`} aria-label="Фильтры"><div className="ui-filter-panel__content">{children}</div>{onReset && <Button type="button" variant="secondary" onClick={onReset}>{resetLabel}</Button>}</section>; }
export function FileUploader({ label, error, hint, value, onChange, className = "", id, ...props }: Omit<InputProps, "type" | "value" | "onChange"> & { hint?: string; value?: File | null; onChange?: ChangeEventHandler<HTMLInputElement> }) { const inputId = id ?? props.name; return <FormField label={label ?? "Файл"} htmlFor={inputId} error={error} hint={hint} className={className}><input id={inputId} className="ui-file-uploader__input" type="file" aria-invalid={Boolean(error)} onChange={onChange} {...props} />{value && <span className="ui-file-uploader__name">{value.name}</span>}</FormField>; }
