import { AlertCircle, CheckCircle2, LoaderCircle, X } from "lucide-react";
import { forwardRef, useEffect, useId, type ReactNode } from "react";
import { Button, IconButton } from "./Button";

export interface FormFieldProps { label: string; htmlFor?: string; error?: string; hint?: string; children: ReactNode; className?: string; }
export function FormField({ label, htmlFor, error, hint, children, className = "" }: FormFieldProps) { return <div className={`ui-field ${className}`}>{label && <label htmlFor={htmlFor}>{label}</label>}{children}{hint && <span className="ui-field__hint">{hint}</span>}{error && <span className="ui-field__error">{error}</span>}</div>; }
export interface TextareaProps extends React.TextareaHTMLAttributes<HTMLTextAreaElement> { label?: string; error?: string; }
export const Textarea = forwardRef<HTMLTextAreaElement, TextareaProps>(function Textarea({ label, error, className = "", id, ...props }, ref) { const textareaId = id ?? props.name; return <FormField label={label ?? ""} htmlFor={textareaId} error={error}><textarea ref={ref} id={textareaId} className={`ui-control ${error ? "ui-control--error" : ""} ${className}`} aria-invalid={Boolean(error)} {...props} /></FormField>; });
Textarea.displayName = "Textarea";
export interface CheckboxProps extends Omit<React.InputHTMLAttributes<HTMLInputElement>, "type"> { label: ReactNode; }
export const Checkbox = forwardRef<HTMLInputElement, CheckboxProps>(function Checkbox({ label, className = "", id, ...props }, ref) { const generatedId = useId(); const checkboxId = id ?? props.name ?? generatedId; return <label className={`ui-checkbox ${className}`} htmlFor={checkboxId}><input ref={ref} id={checkboxId} type="checkbox" {...props} /><span>{label}</span></label>; });
Checkbox.displayName = "Checkbox";

interface OverlayProps { isOpen: boolean; onClose: () => void; title: string; children: ReactNode; className?: string; }
function useEscape(isOpen: boolean, onClose: () => void) { useEffect(() => { if (!isOpen) return; const handler = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, [isOpen, onClose]); }
export function ModalShell({ isOpen, onClose, title, children, className = "" }: OverlayProps) { useEscape(isOpen, onClose); if (!isOpen) return null; return <div className="ui-overlay" role="presentation" onMouseDown={onClose}><section className={`ui-modal ${className}`} role="dialog" aria-modal="true" aria-labelledby="ui-modal-title" onMouseDown={(event) => event.stopPropagation()}><header className="ui-overlay__header"><h2 id="ui-modal-title">{title}</h2><IconButton aria-label="Закрыть диалог" onClick={onClose}><X size={18} /></IconButton></header><div className="ui-overlay__body">{children}</div></section></div>; }
export function Drawer({ isOpen, onClose, title, children, className = "" }: OverlayProps) { useEscape(isOpen, onClose); if (!isOpen) return null; return <div className="ui-overlay" role="presentation" onMouseDown={onClose}><aside className={`ui-drawer ${className}`} role="dialog" aria-modal="true" aria-label={title} onMouseDown={(event) => event.stopPropagation()}><header className="ui-overlay__header"><h2>{title}</h2><IconButton aria-label="Закрыть панель" onClick={onClose}><X size={18} /></IconButton></header><div className="ui-overlay__body">{children}</div></aside></div>; }
export function EmptyState({ title = "Нет данных", description, action }: { title?: string; description?: string; action?: ReactNode }) { return <div className="ui-state"><h3>{title}</h3>{description && <p>{description}</p>}{action}</div>; }
export function ErrorState({ title = "Не удалось загрузить данные", description, action }: { title?: string; description?: string; action?: ReactNode }) { return <div className="ui-state ui-state--error"><AlertCircle aria-hidden="true" size={20} /><h3>{title}</h3>{description && <p>{description}</p>}{action}</div>; }
export function Spinner({ label = "Загрузка" }: { label?: string }) { return <span className="ui-loading" role="status"><LoaderCircle className="ui-spinner" size={18} /><span>{label}</span></span>; }
export function Skeleton({ lines = 3, className = "" }: { lines?: number; className?: string }) { return <div className={`ui-skeleton ${className}`} aria-label="Загрузка" aria-busy="true">{Array.from({ length: lines }, (_, index) => <span key={index} />)}</div>; }
export const PageLoader = ({ label }: { label?: string }) => <div className="ui-page-state"><Spinner label={label} /></div>;
export const PageError = ({ description, action }: { description?: string; action?: ReactNode }) => <div className="ui-page-state"><ErrorState description={description} action={action} /></div>;
export type ToastKind = "success" | "error" | "info";
export function Toast({ message, kind = "info", onClose }: { message: string; kind?: ToastKind; onClose?: () => void }) { return <div className={`ui-toast ui-toast--${kind}`} role="status"><span>{message}</span>{onClose && <IconButton aria-label="Закрыть уведомление" onClick={onClose}><X size={16} /></IconButton>}</div>; }
export function ConfirmDialog({ isOpen, onClose, onConfirm, title, description, confirmLabel = "Подтвердить" }: Omit<OverlayProps, "children"> & { onConfirm: () => void; description?: string; confirmLabel?: string }) { return <ModalShell isOpen={isOpen} onClose={onClose} title={title}><p>{description}</p><div className="ui-dialog-actions"><Button variant="secondary" onClick={onClose}>Отмена</Button><Button variant="danger" onClick={onConfirm}>{confirmLabel}</Button></div></ModalShell>; }
export function UnsavedChangesDialog(props: Omit<React.ComponentProps<typeof ConfirmDialog>, "title" | "description" | "confirmLabel">) { return <ConfirmDialog {...props} title="Есть несохранённые изменения" description="Если продолжить, внесённые изменения будут потеряны." confirmLabel="Продолжить" />; }
export function UserAvatar({ name, src, size = "md" }: { name: string; src?: string; size?: "sm" | "md" | "lg" }) { const initials = name.split(" ").slice(0, 2).map((part) => part[0]).join("").toUpperCase(); return <span className={`ui-avatar ui-avatar--${size}`} aria-label={name}>{src ? <img src={src} alt="" /> : initials}</span>; }
export function RoleBadge({ role }: { role: string }) { return <span className="ui-badge ui-badge--role">{role}</span>; }
export function DepartmentBadge({ department }: { department: string }) { return <span className="ui-badge ui-badge--department">{department}</span>; }
export function AuditActionBadge({ action }: { action: string }) { return <span className="ui-badge ui-badge--audit">{action}</span>; }
export interface PaginationProps { page: number; pageCount: number; onPageChange: (page: number) => void; }
export function Pagination({ page, pageCount, onPageChange }: PaginationProps) { if (pageCount <= 1) return null; return <nav className="ui-pagination" aria-label="Пагинация"><Button variant="secondary" disabled={page <= 1} onClick={() => onPageChange(page - 1)}>Назад</Button><span>{page} / {pageCount}</span><Button variant="secondary" disabled={page >= pageCount} onClick={() => onPageChange(page + 1)}>Вперёд</Button></nav>; }
export interface TableColumn<T> { id: string; header: ReactNode; cell: (row: T) => ReactNode; mobileLabel?: string; }
export interface DataTableProps<T extends { id: string }> { columns: TableColumn<T>[]; rows: T[]; loading?: boolean; error?: string; empty?: ReactNode; toolbar?: ReactNode; pagination?: PaginationProps; renderMobileCard?: (row: T) => ReactNode; className?: string; }
export function TableToolbar({ children, className = "" }: { children: ReactNode; className?: string }) { return <div className={`ui-table-toolbar ${className}`}>{children}</div>; }
export function ResponsiveTable({ children }: { children: ReactNode }) { return <div className="ui-responsive-table">{children}</div>; }
export function MobileCardList<T extends { id: string }>({ rows, renderCard }: { rows: T[]; renderCard: (row: T) => ReactNode }) { return <div className="ui-mobile-cards">{rows.map((row) => <article key={row.id} className="ui-mobile-card">{renderCard(row)}</article>)}</div>; }
export function DataTable<T extends { id: string }>({ columns, rows, loading, error, empty, toolbar, pagination, renderMobileCard, className = "" }: DataTableProps<T>) { if (loading) return <Skeleton />; if (error) return <ErrorState description={error} />; return <div className={`ui-data-table ${className}`}>{toolbar}{rows.length === 0 ? (empty ?? <EmptyState />) : <><ResponsiveTable><table><thead><tr>{columns.map((column) => <th key={column.id}>{column.header}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.id}>{columns.map((column) => <td key={column.id} data-label={column.mobileLabel ?? String(column.header)}>{column.cell(row)}</td>)}</tr>)}</tbody></table></ResponsiveTable>{renderMobileCard && <MobileCardList rows={rows} renderCard={renderMobileCard} />}</>}{pagination && <Pagination {...pagination} />}</div>; }
export function StatusIcon({ status }: { status: "success" | "error" }) { return status === "success" ? <CheckCircle2 aria-hidden="true" size={16} /> : <AlertCircle aria-hidden="true" size={16} />; }
